logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG

server:
    port: 8000

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/price_comparison?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=EET
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                show_sql: true
        open-in-view: false
#    security:
#        oauth2:
#            client:
#                registration:
#                    google:
#                        client-id:
#                        client-secret:
#                    facebook:
#                        client-id:
#                        client-secret:

app:
    jwt:
        token-prefix: Bearer
        token-expiration-days: 21
        secret-key: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure